//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontLineGUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontLineGUI.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Protection.
        /// </summary>
        public static string AboutDataProtection {
            get {
                return ResourceManager.GetString("AboutDataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatIcon.com.
        /// </summary>
        public static string AboutFlatIconHyperlink {
            get {
                return ResourceManager.GetString("AboutFlatIconHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons made by Hopstarter and Dinosoftlabs from.
        /// </summary>
        public static string AboutFlatIconText {
            get {
                return ResourceManager.GetString("AboutFlatIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was established in 2009 to design &amp; distribute software solutions to consumers around the world. The business went through a period of development from 2014 until 2025, leading to the re-release of this product..
        /// </summary>
        public static string AboutFLText {
            get {
                return ResourceManager.GetString("AboutFLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        public static string AboutLicensing {
            get {
                return ResourceManager.GetString("AboutLicensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further information about the application and our company..
        /// </summary>
        public static string AboutPreInfo {
            get {
                return ResourceManager.GetString("AboutPreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string AboutPrivacy {
            get {
                return ResourceManager.GetString("AboutPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademarks property of their respective owners. .
        /// </summary>
        public static string AboutTradeMarkText {
            get {
                return ResourceManager.GetString("AboutTradeMarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided &apos;as-is&apos; without implication or guarantee..
        /// </summary>
        public static string AboutWarranty {
            get {
                return ResourceManager.GetString("AboutWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainAbout {
            get {
                return ResourceManager.GetString("MainAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string MainCopyrightAllRightsReserved {
            get {
                return ResourceManager.GetString("MainCopyrightAllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline Utilities LTD.
        /// </summary>
        public static string MainCopyrightButton {
            get {
                return ResourceManager.GetString("MainCopyrightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Company Website.
        /// </summary>
        public static string MainCopyrightButtonTooltip {
            get {
                return ResourceManager.GetString("MainCopyrightButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Localization.
        /// </summary>
        public static string MainLocalizationTooltip {
            get {
                return ResourceManager.GetString("MainLocalizationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string MainScan {
            get {
                return ResourceManager.GetString("MainScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan, Optimize &amp; Maintain PC Performance.
        /// </summary>
        public static string MainSubtitle {
            get {
                return ResourceManager.GetString("MainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Repository on GitHub.
        /// </summary>
        public static string MainVersionButtonTooltip {
            get {
                return ResourceManager.GetString("MainVersionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the findings below: -.
        /// </summary>
        public static string ScanCompletePreInfo {
            get {
                return ResourceManager.GetString("ScanCompletePreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Complete.
        /// </summary>
        public static string ScanCompleteTitle {
            get {
                return ResourceManager.GetString("ScanCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string ScanLastPerformedNever {
            get {
                return ResourceManager.GetString("ScanLastPerformedNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scan.
        /// </summary>
        public static string ScanMainButton {
            get {
                return ResourceManager.GetString("ScanMainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Items To Scan!.
        /// </summary>
        public static string ScanMainButtonNoSelection {
            get {
                return ResourceManager.GetString("ScanMainButtonNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string ScanMainButtonRecommended {
            get {
                return ResourceManager.GetString("ScanMainButtonRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Last Performed.
        /// </summary>
        public static string ScanMainLastPerformed {
            get {
                return ResourceManager.GetString("ScanMainLastPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Scan Statistics.
        /// </summary>
        public static string ScanMainLastPerformedToolTip {
            get {
                return ResourceManager.GetString("ScanMainLastPerformedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next ».
        /// </summary>
        public static string ScanNextButton {
            get {
                return ResourceManager.GetString("ScanNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Found!.
        /// </summary>
        public static string ScanningErrorCount {
            get {
                return ResourceManager.GetString("ScanningErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk Files Found!.
        /// </summary>
        public static string ScanningJunkFilesFound {
            get {
                return ResourceManager.GetString("ScanningJunkFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently processing the files / settings inside your system..
        /// </summary>
        public static string ScanningPreInfo {
            get {
                return ResourceManager.GetString("ScanningPreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ScanningProgress {
            get {
                return ResourceManager.GetString("ScanningProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Your System.
        /// </summary>
        public static string ScanningTitle {
            get {
                return ResourceManager.GetString("ScanningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string ScanPauseButton {
            get {
                return ResourceManager.GetString("ScanPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Paused.
        /// </summary>
        public static string ScanPausedTitle {
            get {
                return ResourceManager.GetString("ScanPausedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the scan button below to perform a scan. You can change the items to be scanned underneath: -.
        /// </summary>
        public static string ScanPreInfo {
            get {
                return ResourceManager.GetString("ScanPreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Prev.
        /// </summary>
        public static string ScanPrevButton {
            get {
                return ResourceManager.GetString("ScanPrevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ScanResumeButton {
            get {
                return ResourceManager.GetString("ScanResumeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string ScanSelectAllButton {
            get {
                return ResourceManager.GetString("ScanSelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string ScanSelected {
            get {
                return ResourceManager.GetString("ScanSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ScanStatus {
            get {
                return ResourceManager.GetString("ScanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ScanStopButton {
            get {
                return ResourceManager.GetString("ScanStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Stopped.
        /// </summary>
        public static string ScanStoppedTitle {
            get {
                return ResourceManager.GetString("ScanStoppedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scan Below.
        /// </summary>
        public static string ScanTitle {
            get {
                return ResourceManager.GetString("ScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your System.
        /// </summary>
        public static string ScanYourSystem {
            get {
                return ResourceManager.GetString("ScanYourSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        public static string SettingsBackupTab {
            get {
                return ResourceManager.GetString("SettingsBackupTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneralTab {
            get {
                return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the settings for the app below. These are meant to help the system run smoothly..
        /// </summary>
        public static string SettingsPreInfo {
            get {
                return ResourceManager.GetString("SettingsPreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
