<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FrontLineGUI</RootNamespace>
    <AssemblyName>FLCleaner2.1</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Debug\</OutputPath>
    <NoWarn>1701;1702;WFAC010</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Release\</OutputPath>
    <NoWarn>1701;1702;WFAC010</NoWarn>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup>
    <StartupObject>FrontLineGUI.App</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <PlatformTarget>x86</PlatformTarget>
    <RepositoryUrl>https://www.github.com/flutils/flcleaner</RepositoryUrl>
    <PackageTags>registry, cleaner, windows, 10, 11</PackageTags>
    <NeutralLanguage>en</NeutralLanguage>
    <BaseOutputPath>$(SolutionDir)$(Configuration)\</BaseOutputPath>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <Copyright>Frontline Utilities LTD</Copyright>
    <PackageProjectUrl>https://www.frontlinecleaner.com</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
  </PropertyGroup>
<ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
</ItemGroup>
  <ItemGroup>
    <None Remove="Resources\fl.jpg" />
    <None Remove="Resources\icon.png" />
    <None Remove="Resources\loader.gif" />

    <None Remove="Resources\OS\windows-10.png" />
    <None Remove="Resources\OS\windows-11.png" />
    <None Remove="Resources\OS\windows-8.png" />
    <None Remove="Resources\OS\windows-95.png" />
    <None Remove="Resources\OS\windows-xp.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Include\Classes\DB\Models\ScanItem.cs" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\fl.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FLCleanEngine\FLCleanEngine.vcxproj">
      <TreatAsUsed>true</TreatAsUsed>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\loader.gif">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\OS\windows-10.png" />
    <Resource Include="Resources\OS\windows-11.png" />
    <Resource Include="Resources\OS\windows-8.png" />
    <Resource Include="Resources\OS\windows-95.png" />
    <Resource Include="Resources\OS\windows-xp.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\registry_errors.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\internet_errors.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\invalid_files.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\recycle_bin.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\windows_errors.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\application_errors.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\dll_errors.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\temp_files.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Scan\internet_cache.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CountryFlag.Wpf" Version="1.0.0" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="OSVersionInfo">
      <HintPath>Lib\OSVersionInfo.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Resources\Localization\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Localization\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
</Project>