#include "StdAfx.h"
#include "scanners.h"

const scanner_id ScannersSet[ ] = 
{
	

#ifdef USE_CE // CleanEngine specific scanners

	//COMCLASS_SCANNER_ID,
	//COMPROG_SCANNER_ID,
	//COMTYPELIB_SCANNER_ID,
	//COMINTERFACE_SCANNER_ID,
	COMOBJECT_SCANNER_ID,
	BANDS_SCANNER_ID,
	
	UNINSTALL_SCANNER_ID,
	BHO_SCANNER_ID,
	SHELLEXT_SCANNER_ID,
	SHAREDDLL_SCANNER_ID,
	APPLICATIONS_SCANNER_ID,
	
	HELP_SCANNER_ID,
	CLIENTS_SCANNER_ID,
#endif
	MRU_SCANNER_ID,
#ifdef USE_CE
	MISSPATH_SCANNER_ID,
	CTRLPANEL_SCANNER_ID,
	DISTUNITS_SCANNER_ID,
	EMPTY_KEYS_SCANNER_ID,
	APPPATH_SCANNER_ID,
	STARTMENU_SCANNER_ID,
	
	FILEASSOC_SCANNER_ID,
	MENUHND_SCANNER_ID,
	BROKENSHCUTS_SCANNER_ID,
#endif
	GENERALTEMP_SCANNER_ID,
	RECYCLEBIN_SCANNER_ID,
	DOWNLOAD_SCANNER_ID,
	IECOOKIES_SCANNER_ID,
	IEHISTORY_SCANNER_ID,
	TEMPIE_SCANNER_ID,
	PRFTCHSTUFF_SCANNER_ID,
#ifdef USE_CE
	TEMPWUPDATE_SCANNER_ID,
#endif
	

#ifdef USE_DC // DriveCleaner specific scanners

	CLIPBOARD_SCANNER_ID,
	APP_SCANNER_ID,
	MOZILLA_BROWSERS_SCANNER_ID,
	OPERA_SCANNER_ID,
	CUSTOMFILES_SCANNER_ID,
	IE_SCANNER_ID,
	MESSENGER_SCANNER_ID,
	TEMP_FILES_SCANNER_ID,
	IE_AUTOFILL_SCANNER_ID,
#endif // USE_DC

	TEMPICQ_SCANNER_ID,
	CUSTOMTEMP_SCANNER_ID,
	RECENTDOC_SCANNER_ID
};

size_t const TotalScannersNum = 
    sizeof( ScannersSet ) / sizeof ( ScannersSet[ 0 ] );
