//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontLineGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontLineGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _216 {
            get {
                object obj = ResourceManager.GetObject("216", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anniversary {
            get {
                object obj = ResourceManager.GetObject("anniversary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_errors {
            get {
                object obj = ResourceManager.GetObject("application_errors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backup_icon {
            get {
                object obj = ResourceManager.GetObject("backup_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clean_registry_icon {
            get {
                object obj = ResourceManager.GetObject("clean_registry_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9.53,12.01L5.982,8.462l-3.53,3.53L0.009,9.549l3.53-3.53L-0.01,2.47,2.433,0.027,5.982,3.576,9.549,0.009l2.443,2.443L8.425,6.019l3.548,3.548Z.
        /// </summary>
        public static string CloseButtonPathData {
            get {
                return ResourceManager.GetString("CloseButtonPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0.343,30.913a24.97,24.97,0,1,0,49.94,0,25.177,25.177,0,0,0-25-25.2A25.117,25.117,0,0,0,.343,30.913Zm5.418,0a19.518,19.518,0,1,1,19.517,19.67A19.566,19.566,0,0,1,5.761,30.913Zm7.154,0.14A13.064,13.064,0,0,0,25.9,44.143a11.4,11.4,0,0,0,7.918-2.94,1.427,1.427,0,0,0,.069-1.96l-2.5-2.8a1.274,1.274,0,0,0-1.736-.14,6.494,6.494,0,0,1-3.681,1.12,6.346,6.346,0,0,1-6.39-6.58,6.43,6.43,0,0,1,6.39-6.58,6.2,6.2,0,0,1,3.751,1.12,1.273,1.273,0,0,0,1.736-.14l2.362-2.66a1.389,1.389,0,0,0-.139-2.03,12.339,12.339,0,0,0-7.779- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CompanyURLButtonPathData {
            get {
                return ResourceManager.GetString("CompanyURLButtonPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap defragment_registry_icon {
            get {
                object obj = ResourceManager.GetObject("defragment_registry_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dll_errors {
            get {
                object obj = ResourceManager.GetObject("dll_errors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit_startup_icon {
            get {
                object obj = ResourceManager.GetObject("edit_startup_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap extras_icon {
            get {
                object obj = ResourceManager.GetObject("extras_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap internet_cache {
            get {
                object obj = ResourceManager.GetObject("internet_cache", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap internet_errors {
            get {
                object obj = ResourceManager.GetObject("internet_errors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap invalid_files {
            get {
                object obj = ResourceManager.GetObject("invalid_files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2059,1c70.64-1.771,131.9,19.719,188,37,142.76,43.978,268.92,96.524,385,166,59.84,35.815,136.85,62.613,156,139,6.3,25.124,2.11,57.066-6,77-30.13,74.049-135.42,280.316-33,356,83.49,61.694,236.47-1.36,306-32,30.92-13.627,66.35-36.272,114-23,67.13,18.7,91.9,82.294,124,136,73.93,123.684,133.3,257.89,180,410,16.06,52.31,49.33,158.17,26,215-25.91,63.1-84.71,71.27-147,98-50.13,21.51-90.69,50.42-130,82-24.85,19.96-70.48,70.25-59,121,20.19,89.26,135.96,143.39,217,175,50.78,19.81,99.94,25.17,129,66,42.76,60.07,13.35, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LogoIconPathData {
            get {
                return ResourceManager.GetString("LogoIconPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M51.4,19.661V4.68H0.985V86.818h19.3V52.16H49.879V37.434H20.289V19.661H51.4Zm52.3,8.76A38.844,38.844,0,0,0,92.4,26.9c-5.842,0-10.668,6.474-12.7,9.9l-2.54-8H61.032c0.381,2.92,1.651,7.236,1.651,12.949V86.818h17.4v-34.4c1.27-3.3,4.191-12.314,10.541-12.314,2.921,0,5.08.508,7.239,2.412Zm64.244,29.072c0-16.884-8.128-30.6-30.1-30.6-21.59,0-30.226,14.472-30.226,30.6,0,16.758,8.509,31.23,30.226,31.23C159.438,88.722,167.947,74.123,167.947,57.492Zm-17.779,0c0,14.092-5.588,18.027-12.319,18.027-7.874,0-12.446-5.332-12.44 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LogoTextPathData {
            get {
                return ResourceManager.GetString("LogoTextPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M28,2h-6c-1.104,0-2,0.896-2,2s0.896,2,2,2h1.2l-4.6,4.601C18.28,10.921,18,11.344,18,12c0,1.094,0.859,2,2,2  c0.641,0,1.049-0.248,1.4-0.6L26,8.8V10c0,1.104,0.896,2,2,2s2-0.896,2-2V4C30,2.896,29.104,2,28,2z M12,18  c-0.641,0-1.049,0.248-1.4,0.6L6,23.2V22c0-1.104-0.896-2-2-2s-2,0.896-2,2v6c0,1.104,0.896,2,2,2h6c1.104,0,2-0.896,2-2  s-0.896-2-2-2H8.8l4.6-4.601C13.72,21.079,14,20.656,14,20C14,18.906,13.141,18,12,18z.
        /// </summary>
        public static string MaximizeButtonPathData {
            get {
                return ResourceManager.GetString("MaximizeButtonPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M10.625,1.3A1.525,1.525,0,0,0,10.458.755,0.709,0.709,0,0,0,10.173.467,0.885,0.885,0,0,0,9.77.383H1.59a0.747,0.747,0,0,0-.708.39A2.962,2.962,0,0,0,.666,2.11,3.072,3.072,0,0,0,.883,3.473a0.744,0.744,0,0,0,.708.4H9.77a0.73,0.73,0,0,0,.688-0.39,3.071,3.071,0,0,0,.216-1.372A5.807,5.807,0,0,0,10.625,1.3Z.
        /// </summary>
        public static string MinimizeButtonPathData {
            get {
                return ResourceManager.GetString("MinimizeButtonPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap recycle_bin {
            get {
                object obj = ResourceManager.GetObject("recycle_bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap registry_errors {
            get {
                object obj = ResourceManager.GetObject("registry_errors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap remove_junk_icon {
            get {
                object obj = ResourceManager.GetObject("remove_junk_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap scan_icon {
            get {
                object obj = ResourceManager.GetObject("scan_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap select_all {
            get {
                object obj = ResourceManager.GetObject("select_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap statistics_icon {
            get {
                object obj = ResourceManager.GetObject("statistics_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap temp_files {
            get {
                object obj = ResourceManager.GetObject("temp_files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows_10 {
            get {
                object obj = ResourceManager.GetObject("windows_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows_11 {
            get {
                object obj = ResourceManager.GetObject("windows_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows_8 {
            get {
                object obj = ResourceManager.GetObject("windows_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows_95 {
            get {
                object obj = ResourceManager.GetObject("windows_95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows_errors {
            get {
                object obj = ResourceManager.GetObject("windows_errors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows_xp {
            get {
                object obj = ResourceManager.GetObject("windows_xp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
